// crates/optional/ariadnion-api-files/src/access.rs - Access-ticket contracts for Ariadnion.
//
// Copyright (C) 2026 czxieddan
//
// This file is part of Ariadnion and is provided under version 1.0 of the
// Aperip Heimdall Commons License (AHCL). The applicable version is also subject
// to the AHCL provisions concerning Continuous AHCL Licensing Segments and
// migration to later official versions.
//
// After having a reasonable opportunity to read AHCL, all applicable Additional
// Restrictions, and all version notices, a person accepts the corresponding terms,
// to the extent permitted by applicable law, by using, copying, modifying, building,
// using this file as a dependency, deploying, distributing, or operating this file
// over a network.
//
// Official AHCL English text and public notices: https://ahcl.aperip.com
// Repository verbatim AHCL copy:                 AHCL/AHCL-1.0.md
// Project canonical repository:                  https://github.com/czxieddan/Ariadnion
// AHCL origin and project notice:                AHCL/AHCL-PROJECT-NOTICE.md
// AHCL Version Adoption records:                 AHCL/AHCL-VERSION-ADOPTION.md
// Complete Corresponding Source and history:     AHCL/AHCL-SOURCE.md
// Dependencies, Referenced Materials, and licenses:
//                                                   AHCL/AHCL-DEPENDENCIES.md
// Additional Restrictions:                       Effective; one record applies:
//                                                   AHCL/AHCL-RESTRICTIONS/ARIADNION-AR-2026-001.md (ARIADNION-AR-2026-001)
//
// SPDX-License-Identifier: LicenseRef-AHCL-1.0
//
//! Provider-neutral, tenant-bound file access-ticket values.

use std::fmt::{self, Debug, Formatter};
use std::time::{Duration, SystemTime};

use ariadnion_api_domain::{FileReference, IdempotencyKey};
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::{ApiFilesError, ApiFilesErrorCode};

const MAX_LIFETIME_MICROS: u64 = 900_000_000;
const ENVELOPE_RETENTION_MICROS: i64 = 86_400_000_000;
const TERMINAL_RETENTION_MICROS: i64 = 2_592_000_000_000;

/// An opaque, fixed-width bearer authorizing one file-content read.
///
/// The bytes must be generated by a trusted adapter using a cryptographically
/// secure random source. This contract deliberately exposes only an exact-array
/// constructor and a borrow-only accessor; it does not parse, serialize, clone,
/// display, or otherwise turn the bearer into a general-purpose byte value.
/// Owned storage is zeroized both explicitly and when dropped.
#[derive(Eq, PartialEq)]
pub struct FileAccessTicket([u8; Self::BYTE_LENGTH]);

impl FileAccessTicket {
    /// The exact number of bytes in one access ticket.
    pub const BYTE_LENGTH: usize = 32;

    /// Creates a ticket from exactly 32 bytes supplied by a trusted adapter.
    ///
    /// # Security
    ///
    /// `[u8; 32]` is `Copy`, so this call can leave the source array intact.
    /// Callers must promptly zeroize the source and every derived copy. Raw
    /// bearer bytes may be borrowed only at a reviewed entropy, decode, digest,
    /// or transport-verification boundary, and must never be retained or emitted
    /// through logs, diagnostics, errors, metrics, URLs, or durable rows.
    #[must_use]
    pub const fn new(bytes: [u8; Self::BYTE_LENGTH]) -> Self {
        Self(bytes)
    }

    /// Borrows the exact ticket bytes for a trusted verification adapter.
    ///
    /// # Security
    ///
    /// `[u8; 32]` is `Copy`, so callers must promptly zeroize every derived
    /// copy. Borrow these bytes only at a reviewed entropy, decode, digest, or
    /// transport-verification boundary, and never retain or emit the plaintext
    /// bearer through logs, diagnostics, errors, metrics, URLs, or durable rows.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; Self::BYTE_LENGTH] {
        &self.0
    }
}

impl Debug for FileAccessTicket {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str("FileAccessTicket(<redacted>)")
    }
}

impl Zeroize for FileAccessTicket {
    fn zeroize(&mut self) {
        self.0.zeroize();
    }
}

impl ZeroizeOnDrop for FileAccessTicket {}

impl Drop for FileAccessTicket {
    fn drop(&mut self) {
        self.zeroize();
    }
}

/// The fixed capability audience supported by the first access-ticket slice.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum FileAccessTicketAudience {
    /// Authorizes streaming content for one exact file reference.
    FileContentRead,
}

/// A positive, whole-microsecond access-ticket lifetime bounded to fifteen minutes.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct FileAccessTicketLifetime(Duration);

impl FileAccessTicketLifetime {
    /// The maximum lifetime accepted by this contract.
    pub const MAXIMUM: Duration = Duration::from_secs(15 * 60);

    /// Validates one exact positive whole-microsecond lifetime.
    ///
    /// # Errors
    ///
    /// Returns [`ApiFilesErrorCode::InvalidArgument`] for zero or a duration
    /// with sub-microsecond precision. Returns
    /// [`ApiFilesErrorCode::LimitExceeded`] above fifteen minutes.
    pub fn new(value: Duration) -> Result<Self, ApiFilesError> {
        if value > Self::MAXIMUM {
            return Err(ApiFilesError::new(ApiFilesErrorCode::LimitExceeded));
        }
        if value.is_zero() || !value.subsec_nanos().is_multiple_of(1_000) {
            return Err(ApiFilesError::new(ApiFilesErrorCode::InvalidArgument));
        }
        Ok(Self(value))
    }

    /// Returns the validated lifetime.
    #[must_use]
    pub const fn get(self) -> Duration {
        self.0
    }

    /// Returns the validated lifetime in exact microseconds.
    #[must_use]
    pub const fn as_micros(self) -> u64 {
        self.0.as_micros() as u64
    }
}

/// An exact signed Unix-microsecond validity interval for one access ticket.
///
/// The lower bound is inclusive and the upper bound is exclusive. Both stored
/// bounds are exact whole microseconds and the interval is no longer than the
/// lifetime limit. The constructor also checks that the two bounded retention
/// cutoffs required by later durable adapters remain representable.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct FileAccessTicketValidityWindow {
    issued_at: SystemTime,
    expires_at: SystemTime,
}

impl FileAccessTicketValidityWindow {
    /// Creates a checked validity interval from exact microsecond bounds.
    ///
    /// # Errors
    ///
    /// Returns [`ApiFilesErrorCode::InvalidArgument`] for unaligned,
    /// unrepresentable, equal, reversed, or retention-overflowing bounds.
    /// Returns [`ApiFilesErrorCode::LimitExceeded`] when the interval exceeds
    /// fifteen minutes.
    pub fn new(issued_at: SystemTime, expires_at: SystemTime) -> Result<Self, ApiFilesError> {
        let issued_micros = exact_unix_micros(issued_at)?;
        let expires_micros = exact_unix_micros(expires_at)?;
        checked_window_length(issued_micros, expires_micros)?;
        ensure_retention_cutoffs(expires_micros)?;
        Ok(Self {
            issued_at,
            expires_at,
        })
    }

    /// Returns the inclusive issuance bound.
    #[must_use]
    pub const fn issued_at(self) -> SystemTime {
        self.issued_at
    }

    /// Returns the exclusive expiry bound.
    #[must_use]
    pub const fn expires_at(self) -> SystemTime {
        self.expires_at
    }

    /// Reports whether a timestamp is inside the interval.
    ///
    /// The supplied timestamp is normalized by flooring toward the past to a
    /// signed Unix microsecond. A timestamp outside the representable signed
    /// range cannot authorize this bounded interval and returns `false`.
    #[must_use]
    pub fn is_valid_at(self, now: SystemTime) -> bool {
        let Ok(now_micros) = floor_unix_micros(now) else {
            return false;
        };
        let Ok(issued_micros) = exact_unix_micros(self.issued_at) else {
            return false;
        };
        let Ok(expires_micros) = exact_unix_micros(self.expires_at) else {
            return false;
        };
        issued_micros <= now_micros && now_micros < expires_micros
    }
}

/// One exact file reference, idempotency key, and bounded ticket lifetime.
#[derive(Clone, Eq, PartialEq)]
pub struct FileAccessTicketIssueRequest {
    reference: FileReference,
    idempotency_key: IdempotencyKey,
    lifetime: FileAccessTicketLifetime,
}

impl FileAccessTicketIssueRequest {
    /// Creates a validated issue request for the fixed content-read audience.
    #[must_use]
    pub const fn new(
        reference: FileReference,
        idempotency_key: IdempotencyKey,
        lifetime: FileAccessTicketLifetime,
    ) -> Self {
        Self {
            reference,
            idempotency_key,
            lifetime,
        }
    }

    /// Returns the exact file reference bound to the ticket.
    #[must_use]
    pub const fn reference(&self) -> &FileReference {
        &self.reference
    }

    /// Returns the opaque idempotency key for a trusted durable adapter.
    #[must_use]
    pub const fn idempotency_key(&self) -> &IdempotencyKey {
        &self.idempotency_key
    }

    /// Returns the bounded lifetime requested for the ticket.
    #[must_use]
    pub const fn lifetime(&self) -> FileAccessTicketLifetime {
        self.lifetime
    }
}

impl Debug for FileAccessTicketIssueRequest {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str("FileAccessTicketIssueRequest(<redacted>)")
    }
}

/// A committed ticket, its exact file scope, and its validity interval.
///
/// Grants are intentionally not cloneable. A caller should borrow the ticket
/// for verification and move the grant only across the boundary that owns it.
pub struct FileAccessTicketGrant {
    ticket: FileAccessTicket,
    reference: FileReference,
    validity: FileAccessTicketValidityWindow,
}

impl FileAccessTicketGrant {
    /// Creates a grant for the fixed [`FileAccessTicketAudience::FileContentRead`]
    /// capability.
    #[must_use]
    pub const fn new(
        ticket: FileAccessTicket,
        reference: FileReference,
        validity: FileAccessTicketValidityWindow,
    ) -> Self {
        Self {
            ticket,
            reference,
            validity,
        }
    }

    /// Borrows the opaque bearer ticket.
    #[must_use]
    pub const fn ticket(&self) -> &FileAccessTicket {
        &self.ticket
    }

    /// Returns the exact file reference authorized by this grant.
    #[must_use]
    pub const fn reference(&self) -> &FileReference {
        &self.reference
    }

    /// Returns the fixed capability audience.
    #[must_use]
    pub const fn audience(&self) -> FileAccessTicketAudience {
        FileAccessTicketAudience::FileContentRead
    }

    /// Returns the immutable validity interval.
    #[must_use]
    pub const fn validity(&self) -> FileAccessTicketValidityWindow {
        self.validity
    }
}

impl Debug for FileAccessTicketGrant {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str("FileAccessTicketGrant(<redacted>)")
    }
}

/// The authoritative result of reconciling one issue operation.
pub enum FileAccessTicketIssueReconciliation {
    /// The original committed grant was recovered from authoritative state.
    Committed(FileAccessTicketGrant),
    /// Authoritative state proves that the original issue did not commit.
    NotCommitted,
}

impl Debug for FileAccessTicketIssueReconciliation {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Committed(_) => {
                formatter.write_str("FileAccessTicketIssueReconciliation::Committed(<redacted>)")
            }
            Self::NotCommitted => {
                formatter.write_str("FileAccessTicketIssueReconciliation::NotCommitted")
            }
        }
    }
}

fn checked_window_length(issued_micros: i64, expires_micros: i64) -> Result<i64, ApiFilesError> {
    if issued_micros >= expires_micros {
        return Err(ApiFilesError::new(ApiFilesErrorCode::InvalidArgument));
    }
    let length = expires_micros
        .checked_sub(issued_micros)
        .ok_or_else(|| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))?;
    if length > MAX_LIFETIME_MICROS as i64 {
        return Err(ApiFilesError::new(ApiFilesErrorCode::LimitExceeded));
    }
    Ok(length)
}

fn ensure_retention_cutoffs(expires_micros: i64) -> Result<(), ApiFilesError> {
    expires_micros
        .checked_add(ENVELOPE_RETENTION_MICROS)
        .ok_or_else(|| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))?;
    expires_micros
        .checked_add(TERMINAL_RETENTION_MICROS)
        .ok_or_else(|| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))?;
    Ok(())
}

fn exact_unix_micros(value: SystemTime) -> Result<i64, ApiFilesError> {
    let (duration, before_epoch) = match value.duration_since(SystemTime::UNIX_EPOCH) {
        Ok(duration) => (duration, false),
        Err(error) => (error.duration(), true),
    };
    if duration.subsec_nanos() % 1_000 != 0 {
        return Err(ApiFilesError::new(ApiFilesErrorCode::InvalidArgument));
    }
    signed_micros(duration, before_epoch)
}

fn floor_unix_micros(value: SystemTime) -> Result<i64, ApiFilesError> {
    let (duration, before_epoch) = match value.duration_since(SystemTime::UNIX_EPOCH) {
        Ok(duration) => (duration, false),
        Err(error) => (error.duration(), true),
    };
    if before_epoch {
        let micros = duration
            .as_micros()
            .checked_add(u128::from(!duration.subsec_nanos().is_multiple_of(1_000)))
            .ok_or_else(|| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))?;
        signed_negative_micros(micros)
    } else {
        signed_micros(duration, false)
    }
}

fn signed_micros(duration: Duration, before_epoch: bool) -> Result<i64, ApiFilesError> {
    let micros = duration.as_micros();
    if before_epoch {
        signed_negative_micros(micros)
    } else {
        i64::try_from(micros).map_err(|_| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))
    }
}

fn signed_negative_micros(micros: u128) -> Result<i64, ApiFilesError> {
    let minimum_magnitude = (i64::MAX as u128) + 1;
    if micros == minimum_magnitude {
        return Ok(i64::MIN);
    }
    let magnitude = i64::try_from(micros)
        .map_err(|_| ApiFilesError::new(ApiFilesErrorCode::InvalidArgument))?;
    Ok(-magnitude)
}
